deploy_production:
  stage: deploy
  image: node:24

  before_script:
    - npm install -g pnpm@latest
    - pnpm --version
    - pnpm install

  script:
    # Build first
    - pnpm build

    # Then inject placeholders into build output
    - node scripts/inject-env.js production
    - pnpm exec wrangler deploy -c build/server/wrangler.json
